FROM node:24.16.0-bookworm-slim@sha256:2c87ef9bd3c6a3bd4b472b4bec2ce9d16354b0c574f736c476489d09f560a203
RUN apt-get update && apt-get install -y --no-install-recommends openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/forest-prisma
RUN npm install --save-exact prisma@7.10.0
ENTRYPOINT ["node", "/opt/forest-prisma/node_modules/prisma/build/index.js"]
